spring.application.name=sitpass-bek

spring.datasource.url=jdbc:postgresql://localhost:5432/sitPassDB?createDatabaseIfNotExist=true
spring.datasource.username=postgres
spring.datasource.password=postgres

#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql
#
#

upload.dir=src/main/resources/images

spring.servlet.multipart.max-file-size=900MB
# Maximum request size in bytes
spring.servlet.multipart.max-request-size=900MB

# ELASTICSEARCH
elasticsearch.host=${ES_HOST:localhost}
elasticsearch.port=${ES_PORT:9200}
elasticsearch.userName=${ES_USERNAME:}
elasticsearch.password=${ES_PASSWORD:}

# DOCUMENT STORAGE - MINIO
spring.minio.url=http://${MINIO_HOST:localhost}:9000
spring.minio.bucket=${MINIO_BUCKET:dddemo-file-items}
spring.minio.access-key=${MINIO_ACCESS_KEY:ROOTUSER}
spring.minio.secret-key=${MINIO_SECRET_KEY:CHANGEME123}

