spring.application.name=sitpass-bek

spring.datasource.url=jdbc:postgresql://localhost:5432/sitPassDB
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
#
#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql



